CREATE SCHEMA auxiliar
  AUTHORIZATION postgres;

COMMENT ON SCHEMA auxiliar
  IS 'Contém tabelas criadas apenas como auxiliares em consultas ou para facilitar o uso do sistema';

CREATE TABLE auxiliar.diario_matriz
(
  id bigint,
  nome character varying(50),
  q01 numeric(20,2),
  q02 numeric(20,2),
  q03 numeric(20,2),
  q04 numeric(20,2),
  q05 numeric(20,2),
  q06 numeric(20,2),
  q07 numeric(20,2),
  q08 numeric(20,2),
  q09 numeric(20,2),
  q10 numeric(20,2),
  q11 numeric(20,2),
  q12 numeric(20,2),
  q13 numeric(20,2),
  q14 numeric(20,2),
  q15 numeric(20,2),
  q16 numeric(20,2),
  q17 numeric(20,2),
  q18 numeric(20,2),
  q19 numeric(20,2),
  q20 numeric(20,2),
  q21 numeric(20,2),
  q22 numeric(20,2),
  q23 numeric(20,2),
  q24 numeric(20,2),
  q25 numeric(20,2),
  q26 numeric(20,2),
  q27 numeric(20,2),
  q28 numeric(20,2),
  q29 numeric(20,2),
  q30 numeric(20,2),
  q31 numeric(20,2),
  qtotal numeric(20,2),
  v01 numeric(20,2),
  v02 numeric(20,2),
  v03 numeric(20,2),
  v04 numeric(20,2),
  v05 numeric(20,2),
  v06 numeric(20,2),
  v07 numeric(20,2),
  v08 numeric(20,2),
  v09 numeric(20,2),
  v10 numeric(20,2),
  v11 numeric(20,2),
  v12 numeric(20,2),
  v13 numeric(20,2),
  v14 numeric(20,2),
  v15 numeric(20,2),
  v16 numeric(20,2),
  v17 numeric(20,2),
  v18 numeric(20,2),
  v19 numeric(20,2),
  v20 numeric(20,2),
  v21 numeric(20,2),
  v22 numeric(20,2),
  v23 numeric(20,2),
  v24 numeric(20,2),
  v25 numeric(20,2),
  v26 numeric(20,2),
  v27 numeric(20,2),
  v28 numeric(20,2),
  v29 numeric(20,2),
  v30 numeric(20,2),
  v31 numeric(20,2),
  vtotal numeric(20,2)
)
WITH (
  OIDS=FALSE
);
ALTER TABLE auxiliar.diario_matriz
  OWNER TO postgres;

create function regente.fct_diariobanpop(ano int,mes int) returns setof auxiliar.diario_matriz as $$
select loja_id, l.nome,
sum(case when  extract(day from recebimento) = 01 then cast(qtd as numeric(20,2)) else 0 end) as q01, 
sum(case when  extract(day from recebimento) = 02 then cast(qtd as numeric(20,2)) else 0 end) as q02, 
sum(case when  extract(day from recebimento) = 03 then cast(qtd as numeric(20,2)) else 0 end) as q03, 
sum(case when  extract(day from recebimento) = 04 then cast(qtd as numeric(20,2)) else 0 end) as q04, 
sum(case when  extract(day from recebimento) = 05 then cast(qtd as numeric(20,2)) else 0 end) as q05, 
sum(case when  extract(day from recebimento) = 06 then cast(qtd as numeric(20,2)) else 0 end) as q06, 
sum(case when  extract(day from recebimento) = 07 then cast(qtd as numeric(20,2)) else 0 end) as q07, 
sum(case when  extract(day from recebimento) = 08 then cast(qtd as numeric(20,2)) else 0 end) as q08, 
sum(case when  extract(day from recebimento) = 09 then cast(qtd as numeric(20,2)) else 0 end) as q09, 
sum(case when  extract(day from recebimento) = 10 then cast(qtd as numeric(20,2)) else 0 end) as q10, 
sum(case when  extract(day from recebimento) = 11 then cast(qtd as numeric(20,2)) else 0 end) as q11, 
sum(case when  extract(day from recebimento) = 12 then cast(qtd as numeric(20,2)) else 0 end) as q12, 
sum(case when  extract(day from recebimento) = 13 then cast(qtd as numeric(20,2)) else 0 end) as q13, 
sum(case when  extract(day from recebimento) = 14 then cast(qtd as numeric(20,2)) else 0 end) as q14, 
sum(case when  extract(day from recebimento) = 15 then cast(qtd as numeric(20,2)) else 0 end) as q15, 
sum(case when  extract(day from recebimento) = 16 then cast(qtd as numeric(20,2)) else 0 end) as q16, 
sum(case when  extract(day from recebimento) = 17 then cast(qtd as numeric(20,2)) else 0 end) as q17, 
sum(case when  extract(day from recebimento) = 18 then cast(qtd as numeric(20,2)) else 0 end) as q18, 
sum(case when  extract(day from recebimento) = 19 then cast(qtd as numeric(20,2)) else 0 end) as q19, 
sum(case when  extract(day from recebimento) = 20 then cast(qtd as numeric(20,2)) else 0 end) as q20, 
sum(case when  extract(day from recebimento) = 21 then cast(qtd as numeric(20,2)) else 0 end) as q21, 
sum(case when  extract(day from recebimento) = 22 then cast(qtd as numeric(20,2)) else 0 end) as q22, 
sum(case when  extract(day from recebimento) = 23 then cast(qtd as numeric(20,2)) else 0 end) as q23, 
sum(case when  extract(day from recebimento) = 24 then cast(qtd as numeric(20,2)) else 0 end) as q24, 
sum(case when  extract(day from recebimento) = 25 then cast(qtd as numeric(20,2)) else 0 end) as q25, 
sum(case when  extract(day from recebimento) = 26 then cast(qtd as numeric(20,2)) else 0 end) as q26, 
sum(case when  extract(day from recebimento) = 27 then cast(qtd as numeric(20,2)) else 0 end) as q27, 
sum(case when  extract(day from recebimento) = 28 then cast(qtd as numeric(20,2)) else 0 end) as q28, 
sum(case when  extract(day from recebimento) = 29 then cast(qtd as numeric(20,2)) else 0 end) as q29, 
sum(case when  extract(day from recebimento) = 30 then cast(qtd as numeric(20,2)) else 0 end) as q30, 
sum(case when  extract(day from recebimento) = 31 then cast(qtd as numeric(20,2)) else 0 end) as q31,
sum(cast(qtd as numeric(20,2))) qTotal,
sum(case when  extract(day from recebimento) = 01 then arrecadado else 0 end) as v01, 
sum(case when  extract(day from recebimento) = 02 then arrecadado else 0 end) as v02, 
sum(case when  extract(day from recebimento) = 03 then arrecadado else 0 end) as v03, 
sum(case when  extract(day from recebimento) = 04 then arrecadado else 0 end) as v04, 
sum(case when  extract(day from recebimento) = 05 then arrecadado else 0 end) as v05, 
sum(case when  extract(day from recebimento) = 06 then arrecadado else 0 end) as v06, 
sum(case when  extract(day from recebimento) = 07 then arrecadado else 0 end) as v07, 
sum(case when  extract(day from recebimento) = 08 then arrecadado else 0 end) as v08, 
sum(case when  extract(day from recebimento) = 09 then arrecadado else 0 end) as v09, 
sum(case when  extract(day from recebimento) = 10 then arrecadado else 0 end) as v10, 
sum(case when  extract(day from recebimento) = 11 then arrecadado else 0 end) as v11, 
sum(case when  extract(day from recebimento) = 12 then arrecadado else 0 end) as v12, 
sum(case when  extract(day from recebimento) = 13 then arrecadado else 0 end) as v13, 
sum(case when  extract(day from recebimento) = 14 then arrecadado else 0 end) as v14, 
sum(case when  extract(day from recebimento) = 15 then arrecadado else 0 end) as v15, 
sum(case when  extract(day from recebimento) = 16 then arrecadado else 0 end) as v16, 
sum(case when  extract(day from recebimento) = 17 then arrecadado else 0 end) as v17, 
sum(case when  extract(day from recebimento) = 18 then arrecadado else 0 end) as v18, 
sum(case when  extract(day from recebimento) = 19 then arrecadado else 0 end) as v19, 
sum(case when  extract(day from recebimento) = 20 then arrecadado else 0 end) as v20, 
sum(case when  extract(day from recebimento) = 21 then arrecadado else 0 end) as v21, 
sum(case when  extract(day from recebimento) = 22 then arrecadado else 0 end) as v22, 
sum(case when  extract(day from recebimento) = 23 then arrecadado else 0 end) as v23, 
sum(case when  extract(day from recebimento) = 24 then arrecadado else 0 end) as v24, 
sum(case when  extract(day from recebimento) = 25 then arrecadado else 0 end) as v25, 
sum(case when  extract(day from recebimento) = 26 then arrecadado else 0 end) as v26, 
sum(case when  extract(day from recebimento) = 27 then arrecadado else 0 end) as v27, 
sum(case when  extract(day from recebimento) = 28 then arrecadado else 0 end) as v28, 
sum(case when  extract(day from recebimento) = 29 then arrecadado else 0 end) as v29, 
sum(case when  extract(day from recebimento) = 30 then arrecadado else 0 end) as v30, 
sum(case when  extract(day from recebimento) = 31 then arrecadado else 0 end) as v31,
sum(arrecadado) vTotal
from regente.diariobanpop d
left join cadastro.loja l on (l.id=d.loja_id)
where extract(year from recebimento) = ano and extract(month from recebimento)=mes
group by loja_id, l.nome
order by loja_id;
$$ language sql;

create function regente.fct_diariobb(ano int,mes int) returns setof auxiliar.diario_matriz as $$
select loja_id, l.nome,
sum(case when  extract(day from recebimento) = 01 then cast(qtd as numeric(20,2)) else 0 end) as q01, 
sum(case when  extract(day from recebimento) = 02 then cast(qtd as numeric(20,2)) else 0 end) as q02, 
sum(case when  extract(day from recebimento) = 03 then cast(qtd as numeric(20,2)) else 0 end) as q03, 
sum(case when  extract(day from recebimento) = 04 then cast(qtd as numeric(20,2)) else 0 end) as q04, 
sum(case when  extract(day from recebimento) = 05 then cast(qtd as numeric(20,2)) else 0 end) as q05, 
sum(case when  extract(day from recebimento) = 06 then cast(qtd as numeric(20,2)) else 0 end) as q06, 
sum(case when  extract(day from recebimento) = 07 then cast(qtd as numeric(20,2)) else 0 end) as q07, 
sum(case when  extract(day from recebimento) = 08 then cast(qtd as numeric(20,2)) else 0 end) as q08, 
sum(case when  extract(day from recebimento) = 09 then cast(qtd as numeric(20,2)) else 0 end) as q09, 
sum(case when  extract(day from recebimento) = 10 then cast(qtd as numeric(20,2)) else 0 end) as q10, 
sum(case when  extract(day from recebimento) = 11 then cast(qtd as numeric(20,2)) else 0 end) as q11, 
sum(case when  extract(day from recebimento) = 12 then cast(qtd as numeric(20,2)) else 0 end) as q12, 
sum(case when  extract(day from recebimento) = 13 then cast(qtd as numeric(20,2)) else 0 end) as q13, 
sum(case when  extract(day from recebimento) = 14 then cast(qtd as numeric(20,2)) else 0 end) as q14, 
sum(case when  extract(day from recebimento) = 15 then cast(qtd as numeric(20,2)) else 0 end) as q15, 
sum(case when  extract(day from recebimento) = 16 then cast(qtd as numeric(20,2)) else 0 end) as q16, 
sum(case when  extract(day from recebimento) = 17 then cast(qtd as numeric(20,2)) else 0 end) as q17, 
sum(case when  extract(day from recebimento) = 18 then cast(qtd as numeric(20,2)) else 0 end) as q18, 
sum(case when  extract(day from recebimento) = 19 then cast(qtd as numeric(20,2)) else 0 end) as q19, 
sum(case when  extract(day from recebimento) = 20 then cast(qtd as numeric(20,2)) else 0 end) as q20, 
sum(case when  extract(day from recebimento) = 21 then cast(qtd as numeric(20,2)) else 0 end) as q21, 
sum(case when  extract(day from recebimento) = 22 then cast(qtd as numeric(20,2)) else 0 end) as q22, 
sum(case when  extract(day from recebimento) = 23 then cast(qtd as numeric(20,2)) else 0 end) as q23, 
sum(case when  extract(day from recebimento) = 24 then cast(qtd as numeric(20,2)) else 0 end) as q24, 
sum(case when  extract(day from recebimento) = 25 then cast(qtd as numeric(20,2)) else 0 end) as q25, 
sum(case when  extract(day from recebimento) = 26 then cast(qtd as numeric(20,2)) else 0 end) as q26, 
sum(case when  extract(day from recebimento) = 27 then cast(qtd as numeric(20,2)) else 0 end) as q27, 
sum(case when  extract(day from recebimento) = 28 then cast(qtd as numeric(20,2)) else 0 end) as q28, 
sum(case when  extract(day from recebimento) = 29 then cast(qtd as numeric(20,2)) else 0 end) as q29, 
sum(case when  extract(day from recebimento) = 30 then cast(qtd as numeric(20,2)) else 0 end) as q30, 
sum(case when  extract(day from recebimento) = 31 then cast(qtd as numeric(20,2)) else 0 end) as q31,
sum(cast(qtd as numeric(20,2))) qTotal,
sum(case when  extract(day from recebimento) = 01 then arrecadado else 0 end) as v01, 
sum(case when  extract(day from recebimento) = 02 then arrecadado else 0 end) as v02, 
sum(case when  extract(day from recebimento) = 03 then arrecadado else 0 end) as v03, 
sum(case when  extract(day from recebimento) = 04 then arrecadado else 0 end) as v04, 
sum(case when  extract(day from recebimento) = 05 then arrecadado else 0 end) as v05, 
sum(case when  extract(day from recebimento) = 06 then arrecadado else 0 end) as v06, 
sum(case when  extract(day from recebimento) = 07 then arrecadado else 0 end) as v07, 
sum(case when  extract(day from recebimento) = 08 then arrecadado else 0 end) as v08, 
sum(case when  extract(day from recebimento) = 09 then arrecadado else 0 end) as v09, 
sum(case when  extract(day from recebimento) = 10 then arrecadado else 0 end) as v10, 
sum(case when  extract(day from recebimento) = 11 then arrecadado else 0 end) as v11, 
sum(case when  extract(day from recebimento) = 12 then arrecadado else 0 end) as v12, 
sum(case when  extract(day from recebimento) = 13 then arrecadado else 0 end) as v13, 
sum(case when  extract(day from recebimento) = 14 then arrecadado else 0 end) as v14, 
sum(case when  extract(day from recebimento) = 15 then arrecadado else 0 end) as v15, 
sum(case when  extract(day from recebimento) = 16 then arrecadado else 0 end) as v16, 
sum(case when  extract(day from recebimento) = 17 then arrecadado else 0 end) as v17, 
sum(case when  extract(day from recebimento) = 18 then arrecadado else 0 end) as v18, 
sum(case when  extract(day from recebimento) = 19 then arrecadado else 0 end) as v19, 
sum(case when  extract(day from recebimento) = 20 then arrecadado else 0 end) as v20, 
sum(case when  extract(day from recebimento) = 21 then arrecadado else 0 end) as v21, 
sum(case when  extract(day from recebimento) = 22 then arrecadado else 0 end) as v22, 
sum(case when  extract(day from recebimento) = 23 then arrecadado else 0 end) as v23, 
sum(case when  extract(day from recebimento) = 24 then arrecadado else 0 end) as v24, 
sum(case when  extract(day from recebimento) = 25 then arrecadado else 0 end) as v25, 
sum(case when  extract(day from recebimento) = 26 then arrecadado else 0 end) as v26, 
sum(case when  extract(day from recebimento) = 27 then arrecadado else 0 end) as v27, 
sum(case when  extract(day from recebimento) = 28 then arrecadado else 0 end) as v28, 
sum(case when  extract(day from recebimento) = 29 then arrecadado else 0 end) as v29, 
sum(case when  extract(day from recebimento) = 30 then arrecadado else 0 end) as v30, 
sum(case when  extract(day from recebimento) = 31 then arrecadado else 0 end) as v31,
sum(arrecadado) vTotal
from regente.diariobb d
left join cadastro.loja l on (l.id=d.loja_id)
where extract(year from recebimento) = ano and extract(month from recebimento)=mes
group by loja_id, l.nome
order by loja_id;
$$ language sql;

create function regente.fct_diarioboleto(ano int,mes int) returns setof auxiliar.diario_matriz as $$
select loja_id, l.nome,
sum(case when  extract(day from recebimento) = 01 then cast(qtd as numeric(20,2)) else 0 end) as q01, 
sum(case when  extract(day from recebimento) = 02 then cast(qtd as numeric(20,2)) else 0 end) as q02, 
sum(case when  extract(day from recebimento) = 03 then cast(qtd as numeric(20,2)) else 0 end) as q03, 
sum(case when  extract(day from recebimento) = 04 then cast(qtd as numeric(20,2)) else 0 end) as q04, 
sum(case when  extract(day from recebimento) = 05 then cast(qtd as numeric(20,2)) else 0 end) as q05, 
sum(case when  extract(day from recebimento) = 06 then cast(qtd as numeric(20,2)) else 0 end) as q06, 
sum(case when  extract(day from recebimento) = 07 then cast(qtd as numeric(20,2)) else 0 end) as q07, 
sum(case when  extract(day from recebimento) = 08 then cast(qtd as numeric(20,2)) else 0 end) as q08, 
sum(case when  extract(day from recebimento) = 09 then cast(qtd as numeric(20,2)) else 0 end) as q09, 
sum(case when  extract(day from recebimento) = 10 then cast(qtd as numeric(20,2)) else 0 end) as q10, 
sum(case when  extract(day from recebimento) = 11 then cast(qtd as numeric(20,2)) else 0 end) as q11, 
sum(case when  extract(day from recebimento) = 12 then cast(qtd as numeric(20,2)) else 0 end) as q12, 
sum(case when  extract(day from recebimento) = 13 then cast(qtd as numeric(20,2)) else 0 end) as q13, 
sum(case when  extract(day from recebimento) = 14 then cast(qtd as numeric(20,2)) else 0 end) as q14, 
sum(case when  extract(day from recebimento) = 15 then cast(qtd as numeric(20,2)) else 0 end) as q15, 
sum(case when  extract(day from recebimento) = 16 then cast(qtd as numeric(20,2)) else 0 end) as q16, 
sum(case when  extract(day from recebimento) = 17 then cast(qtd as numeric(20,2)) else 0 end) as q17, 
sum(case when  extract(day from recebimento) = 18 then cast(qtd as numeric(20,2)) else 0 end) as q18, 
sum(case when  extract(day from recebimento) = 19 then cast(qtd as numeric(20,2)) else 0 end) as q19, 
sum(case when  extract(day from recebimento) = 20 then cast(qtd as numeric(20,2)) else 0 end) as q20, 
sum(case when  extract(day from recebimento) = 21 then cast(qtd as numeric(20,2)) else 0 end) as q21, 
sum(case when  extract(day from recebimento) = 22 then cast(qtd as numeric(20,2)) else 0 end) as q22, 
sum(case when  extract(day from recebimento) = 23 then cast(qtd as numeric(20,2)) else 0 end) as q23, 
sum(case when  extract(day from recebimento) = 24 then cast(qtd as numeric(20,2)) else 0 end) as q24, 
sum(case when  extract(day from recebimento) = 25 then cast(qtd as numeric(20,2)) else 0 end) as q25, 
sum(case when  extract(day from recebimento) = 26 then cast(qtd as numeric(20,2)) else 0 end) as q26, 
sum(case when  extract(day from recebimento) = 27 then cast(qtd as numeric(20,2)) else 0 end) as q27, 
sum(case when  extract(day from recebimento) = 28 then cast(qtd as numeric(20,2)) else 0 end) as q28, 
sum(case when  extract(day from recebimento) = 29 then cast(qtd as numeric(20,2)) else 0 end) as q29, 
sum(case when  extract(day from recebimento) = 30 then cast(qtd as numeric(20,2)) else 0 end) as q30, 
sum(case when  extract(day from recebimento) = 31 then cast(qtd as numeric(20,2)) else 0 end) as q31,
sum(cast(qtd as numeric(20,2))) qTotal,
sum(case when  extract(day from recebimento) = 01 then arrecadado else 0 end) as v01, 
sum(case when  extract(day from recebimento) = 02 then arrecadado else 0 end) as v02, 
sum(case when  extract(day from recebimento) = 03 then arrecadado else 0 end) as v03, 
sum(case when  extract(day from recebimento) = 04 then arrecadado else 0 end) as v04, 
sum(case when  extract(day from recebimento) = 05 then arrecadado else 0 end) as v05, 
sum(case when  extract(day from recebimento) = 06 then arrecadado else 0 end) as v06, 
sum(case when  extract(day from recebimento) = 07 then arrecadado else 0 end) as v07, 
sum(case when  extract(day from recebimento) = 08 then arrecadado else 0 end) as v08, 
sum(case when  extract(day from recebimento) = 09 then arrecadado else 0 end) as v09, 
sum(case when  extract(day from recebimento) = 10 then arrecadado else 0 end) as v10, 
sum(case when  extract(day from recebimento) = 11 then arrecadado else 0 end) as v11, 
sum(case when  extract(day from recebimento) = 12 then arrecadado else 0 end) as v12, 
sum(case when  extract(day from recebimento) = 13 then arrecadado else 0 end) as v13, 
sum(case when  extract(day from recebimento) = 14 then arrecadado else 0 end) as v14, 
sum(case when  extract(day from recebimento) = 15 then arrecadado else 0 end) as v15, 
sum(case when  extract(day from recebimento) = 16 then arrecadado else 0 end) as v16, 
sum(case when  extract(day from recebimento) = 17 then arrecadado else 0 end) as v17, 
sum(case when  extract(day from recebimento) = 18 then arrecadado else 0 end) as v18, 
sum(case when  extract(day from recebimento) = 19 then arrecadado else 0 end) as v19, 
sum(case when  extract(day from recebimento) = 20 then arrecadado else 0 end) as v20, 
sum(case when  extract(day from recebimento) = 21 then arrecadado else 0 end) as v21, 
sum(case when  extract(day from recebimento) = 22 then arrecadado else 0 end) as v22, 
sum(case when  extract(day from recebimento) = 23 then arrecadado else 0 end) as v23, 
sum(case when  extract(day from recebimento) = 24 then arrecadado else 0 end) as v24, 
sum(case when  extract(day from recebimento) = 25 then arrecadado else 0 end) as v25, 
sum(case when  extract(day from recebimento) = 26 then arrecadado else 0 end) as v26, 
sum(case when  extract(day from recebimento) = 27 then arrecadado else 0 end) as v27, 
sum(case when  extract(day from recebimento) = 28 then arrecadado else 0 end) as v28, 
sum(case when  extract(day from recebimento) = 29 then arrecadado else 0 end) as v29, 
sum(case when  extract(day from recebimento) = 30 then arrecadado else 0 end) as v30, 
sum(case when  extract(day from recebimento) = 31 then arrecadado else 0 end) as v31,
sum(arrecadado) vTotal
from regente.diarioboleto d
left join cadastro.loja l on (l.id=d.loja_id)
where extract(year from recebimento) = ano and extract(month from recebimento)=mes
group by loja_id, l.nome
order by loja_id;
$$ language sql;

create function regente.fct_diariocredito(ano int,mes int) returns setof auxiliar.diario_matriz as $$
select loja_id, l.nome,
sum(case when  extract(day from recebimento) = 01 then cast(qtd as numeric(20,2)) else 0 end) as q01, 
sum(case when  extract(day from recebimento) = 02 then cast(qtd as numeric(20,2)) else 0 end) as q02, 
sum(case when  extract(day from recebimento) = 03 then cast(qtd as numeric(20,2)) else 0 end) as q03, 
sum(case when  extract(day from recebimento) = 04 then cast(qtd as numeric(20,2)) else 0 end) as q04, 
sum(case when  extract(day from recebimento) = 05 then cast(qtd as numeric(20,2)) else 0 end) as q05, 
sum(case when  extract(day from recebimento) = 06 then cast(qtd as numeric(20,2)) else 0 end) as q06, 
sum(case when  extract(day from recebimento) = 07 then cast(qtd as numeric(20,2)) else 0 end) as q07, 
sum(case when  extract(day from recebimento) = 08 then cast(qtd as numeric(20,2)) else 0 end) as q08, 
sum(case when  extract(day from recebimento) = 09 then cast(qtd as numeric(20,2)) else 0 end) as q09, 
sum(case when  extract(day from recebimento) = 10 then cast(qtd as numeric(20,2)) else 0 end) as q10, 
sum(case when  extract(day from recebimento) = 11 then cast(qtd as numeric(20,2)) else 0 end) as q11, 
sum(case when  extract(day from recebimento) = 12 then cast(qtd as numeric(20,2)) else 0 end) as q12, 
sum(case when  extract(day from recebimento) = 13 then cast(qtd as numeric(20,2)) else 0 end) as q13, 
sum(case when  extract(day from recebimento) = 14 then cast(qtd as numeric(20,2)) else 0 end) as q14, 
sum(case when  extract(day from recebimento) = 15 then cast(qtd as numeric(20,2)) else 0 end) as q15, 
sum(case when  extract(day from recebimento) = 16 then cast(qtd as numeric(20,2)) else 0 end) as q16, 
sum(case when  extract(day from recebimento) = 17 then cast(qtd as numeric(20,2)) else 0 end) as q17, 
sum(case when  extract(day from recebimento) = 18 then cast(qtd as numeric(20,2)) else 0 end) as q18, 
sum(case when  extract(day from recebimento) = 19 then cast(qtd as numeric(20,2)) else 0 end) as q19, 
sum(case when  extract(day from recebimento) = 20 then cast(qtd as numeric(20,2)) else 0 end) as q20, 
sum(case when  extract(day from recebimento) = 21 then cast(qtd as numeric(20,2)) else 0 end) as q21, 
sum(case when  extract(day from recebimento) = 22 then cast(qtd as numeric(20,2)) else 0 end) as q22, 
sum(case when  extract(day from recebimento) = 23 then cast(qtd as numeric(20,2)) else 0 end) as q23, 
sum(case when  extract(day from recebimento) = 24 then cast(qtd as numeric(20,2)) else 0 end) as q24, 
sum(case when  extract(day from recebimento) = 25 then cast(qtd as numeric(20,2)) else 0 end) as q25, 
sum(case when  extract(day from recebimento) = 26 then cast(qtd as numeric(20,2)) else 0 end) as q26, 
sum(case when  extract(day from recebimento) = 27 then cast(qtd as numeric(20,2)) else 0 end) as q27, 
sum(case when  extract(day from recebimento) = 28 then cast(qtd as numeric(20,2)) else 0 end) as q28, 
sum(case when  extract(day from recebimento) = 29 then cast(qtd as numeric(20,2)) else 0 end) as q29, 
sum(case when  extract(day from recebimento) = 30 then cast(qtd as numeric(20,2)) else 0 end) as q30, 
sum(case when  extract(day from recebimento) = 31 then cast(qtd as numeric(20,2)) else 0 end) as q31,
sum(cast(qtd as numeric(20,2))) qTotal,
sum(case when  extract(day from recebimento) = 01 then arrecadado else 0 end) as v01, 
sum(case when  extract(day from recebimento) = 02 then arrecadado else 0 end) as v02, 
sum(case when  extract(day from recebimento) = 03 then arrecadado else 0 end) as v03, 
sum(case when  extract(day from recebimento) = 04 then arrecadado else 0 end) as v04, 
sum(case when  extract(day from recebimento) = 05 then arrecadado else 0 end) as v05, 
sum(case when  extract(day from recebimento) = 06 then arrecadado else 0 end) as v06, 
sum(case when  extract(day from recebimento) = 07 then arrecadado else 0 end) as v07, 
sum(case when  extract(day from recebimento) = 08 then arrecadado else 0 end) as v08, 
sum(case when  extract(day from recebimento) = 09 then arrecadado else 0 end) as v09, 
sum(case when  extract(day from recebimento) = 10 then arrecadado else 0 end) as v10, 
sum(case when  extract(day from recebimento) = 11 then arrecadado else 0 end) as v11, 
sum(case when  extract(day from recebimento) = 12 then arrecadado else 0 end) as v12, 
sum(case when  extract(day from recebimento) = 13 then arrecadado else 0 end) as v13, 
sum(case when  extract(day from recebimento) = 14 then arrecadado else 0 end) as v14, 
sum(case when  extract(day from recebimento) = 15 then arrecadado else 0 end) as v15, 
sum(case when  extract(day from recebimento) = 16 then arrecadado else 0 end) as v16, 
sum(case when  extract(day from recebimento) = 17 then arrecadado else 0 end) as v17, 
sum(case when  extract(day from recebimento) = 18 then arrecadado else 0 end) as v18, 
sum(case when  extract(day from recebimento) = 19 then arrecadado else 0 end) as v19, 
sum(case when  extract(day from recebimento) = 20 then arrecadado else 0 end) as v20, 
sum(case when  extract(day from recebimento) = 21 then arrecadado else 0 end) as v21, 
sum(case when  extract(day from recebimento) = 22 then arrecadado else 0 end) as v22, 
sum(case when  extract(day from recebimento) = 23 then arrecadado else 0 end) as v23, 
sum(case when  extract(day from recebimento) = 24 then arrecadado else 0 end) as v24, 
sum(case when  extract(day from recebimento) = 25 then arrecadado else 0 end) as v25, 
sum(case when  extract(day from recebimento) = 26 then arrecadado else 0 end) as v26, 
sum(case when  extract(day from recebimento) = 27 then arrecadado else 0 end) as v27, 
sum(case when  extract(day from recebimento) = 28 then arrecadado else 0 end) as v28, 
sum(case when  extract(day from recebimento) = 29 then arrecadado else 0 end) as v29, 
sum(case when  extract(day from recebimento) = 30 then arrecadado else 0 end) as v30, 
sum(case when  extract(day from recebimento) = 31 then arrecadado else 0 end) as v31,
sum(arrecadado) vTotal
from regente.diariocredito d
left join cadastro.loja l on (l.id=d.loja_id)
where extract(year from recebimento) = ano and extract(month from recebimento)=mes
group by loja_id, l.nome
order by loja_id;
$$ language sql;

create function regente.fct_diarioop(ano int,mes int) returns setof auxiliar.diario_matriz as $$
select loja_id, l.nome,
sum(case when  extract(day from recebimento) = 01 then cast(qtd as numeric(20,2)) else 0 end) as q01, 
sum(case when  extract(day from recebimento) = 02 then cast(qtd as numeric(20,2)) else 0 end) as q02, 
sum(case when  extract(day from recebimento) = 03 then cast(qtd as numeric(20,2)) else 0 end) as q03, 
sum(case when  extract(day from recebimento) = 04 then cast(qtd as numeric(20,2)) else 0 end) as q04, 
sum(case when  extract(day from recebimento) = 05 then cast(qtd as numeric(20,2)) else 0 end) as q05, 
sum(case when  extract(day from recebimento) = 06 then cast(qtd as numeric(20,2)) else 0 end) as q06, 
sum(case when  extract(day from recebimento) = 07 then cast(qtd as numeric(20,2)) else 0 end) as q07, 
sum(case when  extract(day from recebimento) = 08 then cast(qtd as numeric(20,2)) else 0 end) as q08, 
sum(case when  extract(day from recebimento) = 09 then cast(qtd as numeric(20,2)) else 0 end) as q09, 
sum(case when  extract(day from recebimento) = 10 then cast(qtd as numeric(20,2)) else 0 end) as q10, 
sum(case when  extract(day from recebimento) = 11 then cast(qtd as numeric(20,2)) else 0 end) as q11, 
sum(case when  extract(day from recebimento) = 12 then cast(qtd as numeric(20,2)) else 0 end) as q12, 
sum(case when  extract(day from recebimento) = 13 then cast(qtd as numeric(20,2)) else 0 end) as q13, 
sum(case when  extract(day from recebimento) = 14 then cast(qtd as numeric(20,2)) else 0 end) as q14, 
sum(case when  extract(day from recebimento) = 15 then cast(qtd as numeric(20,2)) else 0 end) as q15, 
sum(case when  extract(day from recebimento) = 16 then cast(qtd as numeric(20,2)) else 0 end) as q16, 
sum(case when  extract(day from recebimento) = 17 then cast(qtd as numeric(20,2)) else 0 end) as q17, 
sum(case when  extract(day from recebimento) = 18 then cast(qtd as numeric(20,2)) else 0 end) as q18, 
sum(case when  extract(day from recebimento) = 19 then cast(qtd as numeric(20,2)) else 0 end) as q19, 
sum(case when  extract(day from recebimento) = 20 then cast(qtd as numeric(20,2)) else 0 end) as q20, 
sum(case when  extract(day from recebimento) = 21 then cast(qtd as numeric(20,2)) else 0 end) as q21, 
sum(case when  extract(day from recebimento) = 22 then cast(qtd as numeric(20,2)) else 0 end) as q22, 
sum(case when  extract(day from recebimento) = 23 then cast(qtd as numeric(20,2)) else 0 end) as q23, 
sum(case when  extract(day from recebimento) = 24 then cast(qtd as numeric(20,2)) else 0 end) as q24, 
sum(case when  extract(day from recebimento) = 25 then cast(qtd as numeric(20,2)) else 0 end) as q25, 
sum(case when  extract(day from recebimento) = 26 then cast(qtd as numeric(20,2)) else 0 end) as q26, 
sum(case when  extract(day from recebimento) = 27 then cast(qtd as numeric(20,2)) else 0 end) as q27, 
sum(case when  extract(day from recebimento) = 28 then cast(qtd as numeric(20,2)) else 0 end) as q28, 
sum(case when  extract(day from recebimento) = 29 then cast(qtd as numeric(20,2)) else 0 end) as q29, 
sum(case when  extract(day from recebimento) = 30 then cast(qtd as numeric(20,2)) else 0 end) as q30, 
sum(case when  extract(day from recebimento) = 31 then cast(qtd as numeric(20,2)) else 0 end) as q31,
sum(cast(qtd as numeric(20,2))) qTotal,
sum(case when  extract(day from recebimento) = 01 then arrecadado else 0 end) as v01, 
sum(case when  extract(day from recebimento) = 02 then arrecadado else 0 end) as v02, 
sum(case when  extract(day from recebimento) = 03 then arrecadado else 0 end) as v03, 
sum(case when  extract(day from recebimento) = 04 then arrecadado else 0 end) as v04, 
sum(case when  extract(day from recebimento) = 05 then arrecadado else 0 end) as v05, 
sum(case when  extract(day from recebimento) = 06 then arrecadado else 0 end) as v06, 
sum(case when  extract(day from recebimento) = 07 then arrecadado else 0 end) as v07, 
sum(case when  extract(day from recebimento) = 08 then arrecadado else 0 end) as v08, 
sum(case when  extract(day from recebimento) = 09 then arrecadado else 0 end) as v09, 
sum(case when  extract(day from recebimento) = 10 then arrecadado else 0 end) as v10, 
sum(case when  extract(day from recebimento) = 11 then arrecadado else 0 end) as v11, 
sum(case when  extract(day from recebimento) = 12 then arrecadado else 0 end) as v12, 
sum(case when  extract(day from recebimento) = 13 then arrecadado else 0 end) as v13, 
sum(case when  extract(day from recebimento) = 14 then arrecadado else 0 end) as v14, 
sum(case when  extract(day from recebimento) = 15 then arrecadado else 0 end) as v15, 
sum(case when  extract(day from recebimento) = 16 then arrecadado else 0 end) as v16, 
sum(case when  extract(day from recebimento) = 17 then arrecadado else 0 end) as v17, 
sum(case when  extract(day from recebimento) = 18 then arrecadado else 0 end) as v18, 
sum(case when  extract(day from recebimento) = 19 then arrecadado else 0 end) as v19, 
sum(case when  extract(day from recebimento) = 20 then arrecadado else 0 end) as v20, 
sum(case when  extract(day from recebimento) = 21 then arrecadado else 0 end) as v21, 
sum(case when  extract(day from recebimento) = 22 then arrecadado else 0 end) as v22, 
sum(case when  extract(day from recebimento) = 23 then arrecadado else 0 end) as v23, 
sum(case when  extract(day from recebimento) = 24 then arrecadado else 0 end) as v24, 
sum(case when  extract(day from recebimento) = 25 then arrecadado else 0 end) as v25, 
sum(case when  extract(day from recebimento) = 26 then arrecadado else 0 end) as v26, 
sum(case when  extract(day from recebimento) = 27 then arrecadado else 0 end) as v27, 
sum(case when  extract(day from recebimento) = 28 then arrecadado else 0 end) as v28, 
sum(case when  extract(day from recebimento) = 29 then arrecadado else 0 end) as v29, 
sum(case when  extract(day from recebimento) = 30 then arrecadado else 0 end) as v30, 
sum(case when  extract(day from recebimento) = 31 then arrecadado else 0 end) as v31,
sum(arrecadado) vTotal
from regente.diarioop d
left join cadastro.loja l on (l.id=d.loja_id)
where extract(year from recebimento) = ano and extract(month from recebimento)=mes
group by loja_id, l.nome
order by loja_id;
$$ language sql;

create function regente.fct_diariorecarga(ano int,mes int) returns setof auxiliar.diario_matriz as $$
select loja_id, l.nome,
sum(case when  extract(day from recebimento) = 01 then cast(qtd as numeric(20,2)) else 0 end) as q01, 
sum(case when  extract(day from recebimento) = 02 then cast(qtd as numeric(20,2)) else 0 end) as q02, 
sum(case when  extract(day from recebimento) = 03 then cast(qtd as numeric(20,2)) else 0 end) as q03, 
sum(case when  extract(day from recebimento) = 04 then cast(qtd as numeric(20,2)) else 0 end) as q04, 
sum(case when  extract(day from recebimento) = 05 then cast(qtd as numeric(20,2)) else 0 end) as q05, 
sum(case when  extract(day from recebimento) = 06 then cast(qtd as numeric(20,2)) else 0 end) as q06, 
sum(case when  extract(day from recebimento) = 07 then cast(qtd as numeric(20,2)) else 0 end) as q07, 
sum(case when  extract(day from recebimento) = 08 then cast(qtd as numeric(20,2)) else 0 end) as q08, 
sum(case when  extract(day from recebimento) = 09 then cast(qtd as numeric(20,2)) else 0 end) as q09, 
sum(case when  extract(day from recebimento) = 10 then cast(qtd as numeric(20,2)) else 0 end) as q10, 
sum(case when  extract(day from recebimento) = 11 then cast(qtd as numeric(20,2)) else 0 end) as q11, 
sum(case when  extract(day from recebimento) = 12 then cast(qtd as numeric(20,2)) else 0 end) as q12, 
sum(case when  extract(day from recebimento) = 13 then cast(qtd as numeric(20,2)) else 0 end) as q13, 
sum(case when  extract(day from recebimento) = 14 then cast(qtd as numeric(20,2)) else 0 end) as q14, 
sum(case when  extract(day from recebimento) = 15 then cast(qtd as numeric(20,2)) else 0 end) as q15, 
sum(case when  extract(day from recebimento) = 16 then cast(qtd as numeric(20,2)) else 0 end) as q16, 
sum(case when  extract(day from recebimento) = 17 then cast(qtd as numeric(20,2)) else 0 end) as q17, 
sum(case when  extract(day from recebimento) = 18 then cast(qtd as numeric(20,2)) else 0 end) as q18, 
sum(case when  extract(day from recebimento) = 19 then cast(qtd as numeric(20,2)) else 0 end) as q19, 
sum(case when  extract(day from recebimento) = 20 then cast(qtd as numeric(20,2)) else 0 end) as q20, 
sum(case when  extract(day from recebimento) = 21 then cast(qtd as numeric(20,2)) else 0 end) as q21, 
sum(case when  extract(day from recebimento) = 22 then cast(qtd as numeric(20,2)) else 0 end) as q22, 
sum(case when  extract(day from recebimento) = 23 then cast(qtd as numeric(20,2)) else 0 end) as q23, 
sum(case when  extract(day from recebimento) = 24 then cast(qtd as numeric(20,2)) else 0 end) as q24, 
sum(case when  extract(day from recebimento) = 25 then cast(qtd as numeric(20,2)) else 0 end) as q25, 
sum(case when  extract(day from recebimento) = 26 then cast(qtd as numeric(20,2)) else 0 end) as q26, 
sum(case when  extract(day from recebimento) = 27 then cast(qtd as numeric(20,2)) else 0 end) as q27, 
sum(case when  extract(day from recebimento) = 28 then cast(qtd as numeric(20,2)) else 0 end) as q28, 
sum(case when  extract(day from recebimento) = 29 then cast(qtd as numeric(20,2)) else 0 end) as q29, 
sum(case when  extract(day from recebimento) = 30 then cast(qtd as numeric(20,2)) else 0 end) as q30, 
sum(case when  extract(day from recebimento) = 31 then cast(qtd as numeric(20,2)) else 0 end) as q31,
sum(cast(qtd as numeric(20,2))) qTotal,
sum(case when  extract(day from recebimento) = 01 then arrecadado else 0 end) as v01, 
sum(case when  extract(day from recebimento) = 02 then arrecadado else 0 end) as v02, 
sum(case when  extract(day from recebimento) = 03 then arrecadado else 0 end) as v03, 
sum(case when  extract(day from recebimento) = 04 then arrecadado else 0 end) as v04, 
sum(case when  extract(day from recebimento) = 05 then arrecadado else 0 end) as v05, 
sum(case when  extract(day from recebimento) = 06 then arrecadado else 0 end) as v06, 
sum(case when  extract(day from recebimento) = 07 then arrecadado else 0 end) as v07, 
sum(case when  extract(day from recebimento) = 08 then arrecadado else 0 end) as v08, 
sum(case when  extract(day from recebimento) = 09 then arrecadado else 0 end) as v09, 
sum(case when  extract(day from recebimento) = 10 then arrecadado else 0 end) as v10, 
sum(case when  extract(day from recebimento) = 11 then arrecadado else 0 end) as v11, 
sum(case when  extract(day from recebimento) = 12 then arrecadado else 0 end) as v12, 
sum(case when  extract(day from recebimento) = 13 then arrecadado else 0 end) as v13, 
sum(case when  extract(day from recebimento) = 14 then arrecadado else 0 end) as v14, 
sum(case when  extract(day from recebimento) = 15 then arrecadado else 0 end) as v15, 
sum(case when  extract(day from recebimento) = 16 then arrecadado else 0 end) as v16, 
sum(case when  extract(day from recebimento) = 17 then arrecadado else 0 end) as v17, 
sum(case when  extract(day from recebimento) = 18 then arrecadado else 0 end) as v18, 
sum(case when  extract(day from recebimento) = 19 then arrecadado else 0 end) as v19, 
sum(case when  extract(day from recebimento) = 20 then arrecadado else 0 end) as v20, 
sum(case when  extract(day from recebimento) = 21 then arrecadado else 0 end) as v21, 
sum(case when  extract(day from recebimento) = 22 then arrecadado else 0 end) as v22, 
sum(case when  extract(day from recebimento) = 23 then arrecadado else 0 end) as v23, 
sum(case when  extract(day from recebimento) = 24 then arrecadado else 0 end) as v24, 
sum(case when  extract(day from recebimento) = 25 then arrecadado else 0 end) as v25, 
sum(case when  extract(day from recebimento) = 26 then arrecadado else 0 end) as v26, 
sum(case when  extract(day from recebimento) = 27 then arrecadado else 0 end) as v27, 
sum(case when  extract(day from recebimento) = 28 then arrecadado else 0 end) as v28, 
sum(case when  extract(day from recebimento) = 29 then arrecadado else 0 end) as v29, 
sum(case when  extract(day from recebimento) = 30 then arrecadado else 0 end) as v30, 
sum(case when  extract(day from recebimento) = 31 then arrecadado else 0 end) as v31,
sum(arrecadado) vTotal
from regente.diariorecarga d
left join cadastro.loja l on (l.id=d.loja_id)
where extract(year from recebimento) = ano and extract(month from recebimento)=mes
group by loja_id, l.nome
order by loja_id;
$$ language sql;

create function regente.fct_diariosite(ano int,mes int) returns setof auxiliar.diario_matriz as $$
select loja_id, l.nome,
sum(case when  extract(day from recebimento) = 01 then cast(qtd as numeric(20,2)) else 0 end) as q01, 
sum(case when  extract(day from recebimento) = 02 then cast(qtd as numeric(20,2)) else 0 end) as q02, 
sum(case when  extract(day from recebimento) = 03 then cast(qtd as numeric(20,2)) else 0 end) as q03, 
sum(case when  extract(day from recebimento) = 04 then cast(qtd as numeric(20,2)) else 0 end) as q04, 
sum(case when  extract(day from recebimento) = 05 then cast(qtd as numeric(20,2)) else 0 end) as q05, 
sum(case when  extract(day from recebimento) = 06 then cast(qtd as numeric(20,2)) else 0 end) as q06, 
sum(case when  extract(day from recebimento) = 07 then cast(qtd as numeric(20,2)) else 0 end) as q07, 
sum(case when  extract(day from recebimento) = 08 then cast(qtd as numeric(20,2)) else 0 end) as q08, 
sum(case when  extract(day from recebimento) = 09 then cast(qtd as numeric(20,2)) else 0 end) as q09, 
sum(case when  extract(day from recebimento) = 10 then cast(qtd as numeric(20,2)) else 0 end) as q10, 
sum(case when  extract(day from recebimento) = 11 then cast(qtd as numeric(20,2)) else 0 end) as q11, 
sum(case when  extract(day from recebimento) = 12 then cast(qtd as numeric(20,2)) else 0 end) as q12, 
sum(case when  extract(day from recebimento) = 13 then cast(qtd as numeric(20,2)) else 0 end) as q13, 
sum(case when  extract(day from recebimento) = 14 then cast(qtd as numeric(20,2)) else 0 end) as q14, 
sum(case when  extract(day from recebimento) = 15 then cast(qtd as numeric(20,2)) else 0 end) as q15, 
sum(case when  extract(day from recebimento) = 16 then cast(qtd as numeric(20,2)) else 0 end) as q16, 
sum(case when  extract(day from recebimento) = 17 then cast(qtd as numeric(20,2)) else 0 end) as q17, 
sum(case when  extract(day from recebimento) = 18 then cast(qtd as numeric(20,2)) else 0 end) as q18, 
sum(case when  extract(day from recebimento) = 19 then cast(qtd as numeric(20,2)) else 0 end) as q19, 
sum(case when  extract(day from recebimento) = 20 then cast(qtd as numeric(20,2)) else 0 end) as q20, 
sum(case when  extract(day from recebimento) = 21 then cast(qtd as numeric(20,2)) else 0 end) as q21, 
sum(case when  extract(day from recebimento) = 22 then cast(qtd as numeric(20,2)) else 0 end) as q22, 
sum(case when  extract(day from recebimento) = 23 then cast(qtd as numeric(20,2)) else 0 end) as q23, 
sum(case when  extract(day from recebimento) = 24 then cast(qtd as numeric(20,2)) else 0 end) as q24, 
sum(case when  extract(day from recebimento) = 25 then cast(qtd as numeric(20,2)) else 0 end) as q25, 
sum(case when  extract(day from recebimento) = 26 then cast(qtd as numeric(20,2)) else 0 end) as q26, 
sum(case when  extract(day from recebimento) = 27 then cast(qtd as numeric(20,2)) else 0 end) as q27, 
sum(case when  extract(day from recebimento) = 28 then cast(qtd as numeric(20,2)) else 0 end) as q28, 
sum(case when  extract(day from recebimento) = 29 then cast(qtd as numeric(20,2)) else 0 end) as q29, 
sum(case when  extract(day from recebimento) = 30 then cast(qtd as numeric(20,2)) else 0 end) as q30, 
sum(case when  extract(day from recebimento) = 31 then cast(qtd as numeric(20,2)) else 0 end) as q31,
sum(cast(qtd as numeric(20,2))) qTotal,
sum(case when  extract(day from recebimento) = 01 then arrecadado else 0 end) as v01, 
sum(case when  extract(day from recebimento) = 02 then arrecadado else 0 end) as v02, 
sum(case when  extract(day from recebimento) = 03 then arrecadado else 0 end) as v03, 
sum(case when  extract(day from recebimento) = 04 then arrecadado else 0 end) as v04, 
sum(case when  extract(day from recebimento) = 05 then arrecadado else 0 end) as v05, 
sum(case when  extract(day from recebimento) = 06 then arrecadado else 0 end) as v06, 
sum(case when  extract(day from recebimento) = 07 then arrecadado else 0 end) as v07, 
sum(case when  extract(day from recebimento) = 08 then arrecadado else 0 end) as v08, 
sum(case when  extract(day from recebimento) = 09 then arrecadado else 0 end) as v09, 
sum(case when  extract(day from recebimento) = 10 then arrecadado else 0 end) as v10, 
sum(case when  extract(day from recebimento) = 11 then arrecadado else 0 end) as v11, 
sum(case when  extract(day from recebimento) = 12 then arrecadado else 0 end) as v12, 
sum(case when  extract(day from recebimento) = 13 then arrecadado else 0 end) as v13, 
sum(case when  extract(day from recebimento) = 14 then arrecadado else 0 end) as v14, 
sum(case when  extract(day from recebimento) = 15 then arrecadado else 0 end) as v15, 
sum(case when  extract(day from recebimento) = 16 then arrecadado else 0 end) as v16, 
sum(case when  extract(day from recebimento) = 17 then arrecadado else 0 end) as v17, 
sum(case when  extract(day from recebimento) = 18 then arrecadado else 0 end) as v18, 
sum(case when  extract(day from recebimento) = 19 then arrecadado else 0 end) as v19, 
sum(case when  extract(day from recebimento) = 20 then arrecadado else 0 end) as v20, 
sum(case when  extract(day from recebimento) = 21 then arrecadado else 0 end) as v21, 
sum(case when  extract(day from recebimento) = 22 then arrecadado else 0 end) as v22, 
sum(case when  extract(day from recebimento) = 23 then arrecadado else 0 end) as v23, 
sum(case when  extract(day from recebimento) = 24 then arrecadado else 0 end) as v24, 
sum(case when  extract(day from recebimento) = 25 then arrecadado else 0 end) as v25, 
sum(case when  extract(day from recebimento) = 26 then arrecadado else 0 end) as v26, 
sum(case when  extract(day from recebimento) = 27 then arrecadado else 0 end) as v27, 
sum(case when  extract(day from recebimento) = 28 then arrecadado else 0 end) as v28, 
sum(case when  extract(day from recebimento) = 29 then arrecadado else 0 end) as v29, 
sum(case when  extract(day from recebimento) = 30 then arrecadado else 0 end) as v30, 
sum(case when  extract(day from recebimento) = 31 then arrecadado else 0 end) as v31,
sum(arrecadado) vTotal
from regente.diariosite d
left join cadastro.loja l on (l.id=d.loja_id)
where extract(year from recebimento) = ano and extract(month from recebimento)=mes
group by loja_id, l.nome
order by loja_id;
$$ language sql;

create function regente.fct_diariovalegas(ano int,mes int) returns setof auxiliar.diario_matriz as $$
select loja_id, l.nome,
sum(case when  extract(day from recebimento) = 01 then cast(qtd as numeric(20,2)) else 0 end) as q01, 
sum(case when  extract(day from recebimento) = 02 then cast(qtd as numeric(20,2)) else 0 end) as q02, 
sum(case when  extract(day from recebimento) = 03 then cast(qtd as numeric(20,2)) else 0 end) as q03, 
sum(case when  extract(day from recebimento) = 04 then cast(qtd as numeric(20,2)) else 0 end) as q04, 
sum(case when  extract(day from recebimento) = 05 then cast(qtd as numeric(20,2)) else 0 end) as q05, 
sum(case when  extract(day from recebimento) = 06 then cast(qtd as numeric(20,2)) else 0 end) as q06, 
sum(case when  extract(day from recebimento) = 07 then cast(qtd as numeric(20,2)) else 0 end) as q07, 
sum(case when  extract(day from recebimento) = 08 then cast(qtd as numeric(20,2)) else 0 end) as q08, 
sum(case when  extract(day from recebimento) = 09 then cast(qtd as numeric(20,2)) else 0 end) as q09, 
sum(case when  extract(day from recebimento) = 10 then cast(qtd as numeric(20,2)) else 0 end) as q10, 
sum(case when  extract(day from recebimento) = 11 then cast(qtd as numeric(20,2)) else 0 end) as q11, 
sum(case when  extract(day from recebimento) = 12 then cast(qtd as numeric(20,2)) else 0 end) as q12, 
sum(case when  extract(day from recebimento) = 13 then cast(qtd as numeric(20,2)) else 0 end) as q13, 
sum(case when  extract(day from recebimento) = 14 then cast(qtd as numeric(20,2)) else 0 end) as q14, 
sum(case when  extract(day from recebimento) = 15 then cast(qtd as numeric(20,2)) else 0 end) as q15, 
sum(case when  extract(day from recebimento) = 16 then cast(qtd as numeric(20,2)) else 0 end) as q16, 
sum(case when  extract(day from recebimento) = 17 then cast(qtd as numeric(20,2)) else 0 end) as q17, 
sum(case when  extract(day from recebimento) = 18 then cast(qtd as numeric(20,2)) else 0 end) as q18, 
sum(case when  extract(day from recebimento) = 19 then cast(qtd as numeric(20,2)) else 0 end) as q19, 
sum(case when  extract(day from recebimento) = 20 then cast(qtd as numeric(20,2)) else 0 end) as q20, 
sum(case when  extract(day from recebimento) = 21 then cast(qtd as numeric(20,2)) else 0 end) as q21, 
sum(case when  extract(day from recebimento) = 22 then cast(qtd as numeric(20,2)) else 0 end) as q22, 
sum(case when  extract(day from recebimento) = 23 then cast(qtd as numeric(20,2)) else 0 end) as q23, 
sum(case when  extract(day from recebimento) = 24 then cast(qtd as numeric(20,2)) else 0 end) as q24, 
sum(case when  extract(day from recebimento) = 25 then cast(qtd as numeric(20,2)) else 0 end) as q25, 
sum(case when  extract(day from recebimento) = 26 then cast(qtd as numeric(20,2)) else 0 end) as q26, 
sum(case when  extract(day from recebimento) = 27 then cast(qtd as numeric(20,2)) else 0 end) as q27, 
sum(case when  extract(day from recebimento) = 28 then cast(qtd as numeric(20,2)) else 0 end) as q28, 
sum(case when  extract(day from recebimento) = 29 then cast(qtd as numeric(20,2)) else 0 end) as q29, 
sum(case when  extract(day from recebimento) = 30 then cast(qtd as numeric(20,2)) else 0 end) as q30, 
sum(case when  extract(day from recebimento) = 31 then cast(qtd as numeric(20,2)) else 0 end) as q31,
sum(cast(qtd as numeric(20,2))) qTotal,
sum(case when  extract(day from recebimento) = 01 then arrecadado else 0 end) as v01, 
sum(case when  extract(day from recebimento) = 02 then arrecadado else 0 end) as v02, 
sum(case when  extract(day from recebimento) = 03 then arrecadado else 0 end) as v03, 
sum(case when  extract(day from recebimento) = 04 then arrecadado else 0 end) as v04, 
sum(case when  extract(day from recebimento) = 05 then arrecadado else 0 end) as v05, 
sum(case when  extract(day from recebimento) = 06 then arrecadado else 0 end) as v06, 
sum(case when  extract(day from recebimento) = 07 then arrecadado else 0 end) as v07, 
sum(case when  extract(day from recebimento) = 08 then arrecadado else 0 end) as v08, 
sum(case when  extract(day from recebimento) = 09 then arrecadado else 0 end) as v09, 
sum(case when  extract(day from recebimento) = 10 then arrecadado else 0 end) as v10, 
sum(case when  extract(day from recebimento) = 11 then arrecadado else 0 end) as v11, 
sum(case when  extract(day from recebimento) = 12 then arrecadado else 0 end) as v12, 
sum(case when  extract(day from recebimento) = 13 then arrecadado else 0 end) as v13, 
sum(case when  extract(day from recebimento) = 14 then arrecadado else 0 end) as v14, 
sum(case when  extract(day from recebimento) = 15 then arrecadado else 0 end) as v15, 
sum(case when  extract(day from recebimento) = 16 then arrecadado else 0 end) as v16, 
sum(case when  extract(day from recebimento) = 17 then arrecadado else 0 end) as v17, 
sum(case when  extract(day from recebimento) = 18 then arrecadado else 0 end) as v18, 
sum(case when  extract(day from recebimento) = 19 then arrecadado else 0 end) as v19, 
sum(case when  extract(day from recebimento) = 20 then arrecadado else 0 end) as v20, 
sum(case when  extract(day from recebimento) = 21 then arrecadado else 0 end) as v21, 
sum(case when  extract(day from recebimento) = 22 then arrecadado else 0 end) as v22, 
sum(case when  extract(day from recebimento) = 23 then arrecadado else 0 end) as v23, 
sum(case when  extract(day from recebimento) = 24 then arrecadado else 0 end) as v24, 
sum(case when  extract(day from recebimento) = 25 then arrecadado else 0 end) as v25, 
sum(case when  extract(day from recebimento) = 26 then arrecadado else 0 end) as v26, 
sum(case when  extract(day from recebimento) = 27 then arrecadado else 0 end) as v27, 
sum(case when  extract(day from recebimento) = 28 then arrecadado else 0 end) as v28, 
sum(case when  extract(day from recebimento) = 29 then arrecadado else 0 end) as v29, 
sum(case when  extract(day from recebimento) = 30 then arrecadado else 0 end) as v30, 
sum(case when  extract(day from recebimento) = 31 then arrecadado else 0 end) as v31,
sum(arrecadado) vTotal
from regente.diariovalegas d
left join cadastro.loja l on (l.id=d.loja_id)
where extract(year from recebimento) = ano and extract(month from recebimento)=mes
group by loja_id, l.nome
order by loja_id;
$$ language sql;

create function regente.fct_diariolojatodos(ano int,mes int) returns setof auxiliar.diario_matriz as $$
select id, nome, sum(q01) q01, sum(q02) q02, sum(q03) q03, sum(q04) q04, sum(q05) q05, sum(q06) q06, sum(q07) q07, sum(q08) q08, sum(q09) q09, sum(q10) q10,
sum(q11) q11, sum(q12) q12, sum(q13) q13, sum(q14) q14, sum(q15) q15, sum(q16) q16, sum(q17) q17, sum(q18) q18, sum(q19) q19, sum(q20) q20,
sum(q21) q21, sum(q22) q22, sum(q23) q23, sum(q24) q24, sum(q25) q25, sum(q26) q26, sum(q27) q27, sum(q28) q28, sum(q29) q29, sum(q30) q30, sum(q31) q31, sum(qTotal) qTotal,
sum(v01) v01, sum(v02) v02, sum(v03) v03, sum(v04) v04, sum(v05) v05, sum(v06) v06, sum(v07) v07, sum(v08) v08, sum(v09) v09, sum(v10) v10,
sum(v11) v11, sum(v12) v12, sum(v13) v13, sum(v14) v14, sum(v15) v15, sum(v16) v16, sum(v17) v17, sum(v18) v18, sum(v19) v19, sum(v20) v20,
sum(v21) v21, sum(v22) v22, sum(v23) v23, sum(v24) v24, sum(v25) v25, sum(v26) v26, sum(v27) v27, sum(v28) v28, sum(v29) v29, sum(v30) v30, sum(v31) v31, sum(vTotal) vTotal from(
select * from regente.fct_diariobanpop(ano,mes)
union all
select * from regente.fct_diariobb(ano,mes)
union all
select * from regente.fct_diarioboleto(ano,mes)
union all
select * from regente.fct_diariocredito(ano,mes)
union all
select * from regente.fct_diarioop(ano,mes)
union all
select * from regente.fct_diariorecarga(ano,mes)
union all
select * from regente.fct_diariosite(ano,mes)
union all
select * from regente.fct_diariovalegas(ano,mes)
) s
group by id, nome
order by id;
$$ language sql;

create function regente.fct_diariolojaguias(ano int,mes int) returns setof auxiliar.diario_matriz as $$
select id, nome, sum(q01) q01, sum(q02) q02, sum(q03) q03, sum(q04) q04, sum(q05) q05, sum(q06) q06, sum(q07) q07, sum(q08) q08, sum(q09) q09, sum(q10) q10,
sum(q11) q11, sum(q12) q12, sum(q13) q13, sum(q14) q14, sum(q15) q15, sum(q16) q16, sum(q17) q17, sum(q18) q18, sum(q19) q19, sum(q20) q20,
sum(q21) q21, sum(q22) q22, sum(q23) q23, sum(q24) q24, sum(q25) q25, sum(q26) q26, sum(q27) q27, sum(q28) q28, sum(q29) q29, sum(q30) q30, sum(q31) q31, sum(qTotal) qTotal,
sum(v01) v01, sum(v02) v02, sum(v03) v03, sum(v04) v04, sum(v05) v05, sum(v06) v06, sum(v07) v07, sum(v08) v08, sum(v09) v09, sum(v10) v10,
sum(v11) v11, sum(v12) v12, sum(v13) v13, sum(v14) v14, sum(v15) v15, sum(v16) v16, sum(v17) v17, sum(v18) v18, sum(v19) v19, sum(v20) v20,
sum(v21) v21, sum(v22) v22, sum(v23) v23, sum(v24) v24, sum(v25) v25, sum(v26) v26, sum(v27) v27, sum(v28) v28, sum(v29) v29, sum(v30) v30, sum(v31) v31, sum(vTotal) vTotal from(
select * from regente.fct_diariobanpop(ano,mes)
union all
select * from regente.fct_diariobb(ano,mes)
union all
select * from regente.fct_diarioboleto(ano,mes)
union all
select * from regente.fct_diariosite(ano,mes)
) s
group by id, nome
order by id;
$$ language sql;

create function regente.fct_diariolojacredirecarga(ano int,mes int) returns setof auxiliar.diario_matriz as $$
select id, nome, sum(q01) q01, sum(q02) q02, sum(q03) q03, sum(q04) q04, sum(q05) q05, sum(q06) q06, sum(q07) q07, sum(q08) q08, sum(q09) q09, sum(q10) q10,
sum(q11) q11, sum(q12) q12, sum(q13) q13, sum(q14) q14, sum(q15) q15, sum(q16) q16, sum(q17) q17, sum(q18) q18, sum(q19) q19, sum(q20) q20,
sum(q21) q21, sum(q22) q22, sum(q23) q23, sum(q24) q24, sum(q25) q25, sum(q26) q26, sum(q27) q27, sum(q28) q28, sum(q29) q29, sum(q30) q30, sum(q31) q31, sum(qTotal) qTotal,
sum(v01) v01, sum(v02) v02, sum(v03) v03, sum(v04) v04, sum(v05) v05, sum(v06) v06, sum(v07) v07, sum(v08) v08, sum(v09) v09, sum(v10) v10,
sum(v11) v11, sum(v12) v12, sum(v13) v13, sum(v14) v14, sum(v15) v15, sum(v16) v16, sum(v17) v17, sum(v18) v18, sum(v19) v19, sum(v20) v20,
sum(v21) v21, sum(v22) v22, sum(v23) v23, sum(v24) v24, sum(v25) v25, sum(v26) v26, sum(v27) v27, sum(v28) v28, sum(v29) v29, sum(v30) v30, sum(v31) v31, sum(vTotal) vTotal 
from(
select * from regente.fct_diariocredito(ano,mes)
union all
select * from regente.fct_diariorecarga(ano,mes)
) s
group by id, nome
order by id;
$$ language sql;